---

- name: import database
  hosts: localhost
  vars_files:
    - "/root/upgrades/defaults.yml"
  tasks:
    - name: Bring in database
      shell: "mysql < {{ dbdump_dir }}/rocky-database.save"

- name: Prepare Permissions
  hosts: galera_all[0]
  tasks:
    - name: flush permissions
      shell: mysql -e 'FLUSH PRIVILEGES;'
