---

- name: import database
  hosts: localhost
  tasks:
    - name: Bring in database
      shell: mysql < /root/rocky-database.save

- name: Prepare Permissions
  hosts: galera_all[0]
  tasks:
    - name: flush permissions
      shell: mysql -e 'FLUSH PRIVILEGES;'
