---

- name: Prepare MQ/DB services
  hosts: localhost
  vars_files:
    - "/root/upgrades/defaults.yml"
  tasks:
    - name: Dump database
      shell: "mysqldump --all-databases > {{ dbdump_dir }}/newton-database.save"
